#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! cargo public-api --version >/dev/null 2>&1; then
  cat >&2 <<'EOF'
error: cargo-public-api is required to generate the Rust exported-surface inventory.

Install it in the qualification environment, then rerun this script:

  cargo install cargo-public-api --locked
EOF
  exit 2
fi

output_dir="${1:-target/public-api}"
rm -rf "$output_dir"
mkdir -p "$output_dir"

crates=(
  protocol:lingonberry-protocol
  identity:lingonberry-identity
  validation:lingonberry-validation
  core:lingonberry-core
  indexer:lingonberry-indexer
  relay:lingonberry-relay
  storage:lingonberry-storage
)

rustc --version --verbose >"$output_dir/rust-toolchain.txt"
cargo public-api --version >"$output_dir/cargo-public-api-version.txt"
git rev-parse HEAD >"$output_dir/commit-sha.txt"

for entry in "${crates[@]}"; do
  short_name="${entry%%:*}"
  package_name="${entry#*:}"
  cargo public-api --package "$package_name" --all-features >"$output_dir/${short_name}.txt"
  test -s "$output_dir/${short_name}.txt"
done

cat >"$output_dir/README.md" <<'EOF'
# Generated Rust public API inventory

This directory was generated by `scripts/generate-rust-public-api.sh`.

Generation records:

- candidate commit: `commit-sha.txt`
- Rust compiler and toolchain: `rust-toolchain.txt`
- cargo-public-api: `cargo-public-api-version.txt`

The crate files are mechanical exported-surface evidence. They do not determine
which items are stable v1.x contracts. Normative classification remains in the
reviewed v1 compatibility documentation.
EOF

printf 'generated Rust public API inventory in %s\n' "$output_dir"
