#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! command -v cargo-public-api >/dev/null 2>&1 && ! cargo public-api --version >/dev/null 2>&1; then
  cat >&2 <<'EOF'
error: cargo-public-api is required to generate the Rust exported-surface inventory.

Install it in the qualification environment, then rerun this script:

  cargo install cargo-public-api --locked

The generated files are evidence inputs. Review and commit them only after confirming
the cargo-public-api version and Rust toolchain used for generation.
EOF
  exit 2
fi

output_dir="${1:-docs/architecture/generated/rust-public-api}"
mkdir -p "$output_dir"

crates=(
  lingonberry-protocol
  lingonberry-identity
  lingonberry-validation
  lingonberry-core
  lingonberry-indexer
  lingonberry-relay
  lingonberry-storage
)

rustc --version --verbose >"$output_dir/RUSTC_VERSION.txt"
cargo public-api --version >"$output_dir/CARGO_PUBLIC_API_VERSION.txt"

for crate in "${crates[@]}"; do
  cargo public-api --package "$crate" --all-features >"$output_dir/${crate}.txt"
done

cat >"$output_dir/README.md" <<EOF
# Generated Rust public API inventory

This directory was generated by \`scripts/generate-rust-public-api.sh\`.

Generation records:

- Rust compiler: \`RUSTC_VERSION.txt\`
- cargo-public-api: \`CARGO_PUBLIC_API_VERSION.txt\`

The files are mechanical exported-surface evidence. They do not determine which
items are stable v1.x contracts. Normative classification remains in the reviewed
v1 compatibility documentation.
EOF

printf 'generated Rust public API inventory in %s\n' "$output_dir"
